#nullable disable
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ComponentDetection.Detectors.Tests.Mocks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.ComponentDetection.Detectors.Tests.Mocks.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integrationTestCompileClasspath - Compile classpath for source set &apos;integration test&apos;.
        ///+--- commons-io:commons-io:2.5
        ///+--- org.kohsuke:github-api:1.94
        ///|    +--- org.apache.commons:commons-lang3:3.7
        ///|    +--- commons-codec:commons-codec:1.7
        ///|    +--- com.fasterxml.jackson.core:jackson-databind:2.9.2
        ///|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0
        ///|    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.2
        ///|    \--- commons-io:commons-io:1.4 -&gt; 2.5
        ///+--- org.zeroturnaround:zt-zip: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GradlewDependencyOutput {
            get {
                return ResourceManager.GetString("GradlewDependencyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to org.apache.maven:maven-compat:jar:3.6.1-SNAPSHOT
        ///+- org.apache.maven:maven-model:jar:3.6.1-SNAPSHOT:compile
        ///+- org.apache.maven:maven-model-builder:jar:3.6.1-SNAPSHOT:compile
        ///|  \- org.apache.maven:maven-builder-support:jar:3.6.1-SNAPSHOT:compile
        ///+- org.apache.maven:maven-settings:jar:3.6.1-SNAPSHOT:compile
        ///+- org.apache.maven:maven-settings-builder:jar:3.6.1-SNAPSHOT:compile
        ///|  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4:compile
        ///|     \- org.sonatype.plexus:plexus-cipher:jar:1.7:compile
        ///+- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MvnCliDependencyOutput {
            get {
                return ResourceManager.GetString("MvnCliDependencyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1&quot;,
        ///  &quot;pip_version&quot;: &quot;24.0&quot;,
        ///  &quot;install&quot;: [
        ///    {
        ///      &quot;download_info&quot;: {
        ///        &quot;url&quot;: &quot;https://files.pythonhosted.org/packages/72/c3/532326adbb2b76f709e3e582aeefd0a85bd7454599ff450d90dd9540f5ed/jupyterlab-4.2.0-py3-none-any.whl&quot;,
        ///        &quot;archive_info&quot;: {
        ///          &quot;hash&quot;: &quot;sha256=0dfe9278e25a145362289c555d9beb505697d269c10e99909766af7c440ad3cc&quot;,
        ///          &quot;hashes&quot;: {
        ///            &quot;sha256&quot;: &quot;0dfe9278e25a145362289c555d9beb505697d269c10e99909766af7c440ad3cc&quot;
        ///          }
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pip_report_jupyterlab {
            get {
                return ResourceManager.GetString("pip_report_jupyterlab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1&quot;,
        ///  &quot;pip_version&quot;: &quot;24.0&quot;,
        ///  &quot;install&quot;: [
        ///    {
        ///      &quot;download_info&quot;: {
        ///        &quot;url&quot;: &quot;https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl&quot;,
        ///        &quot;archive_info&quot;: {
        ///          &quot;hash&quot;: &quot;sha256=8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254&quot;,
        ///          &quot;hashes&quot;: {
        ///            &quot;sha256&quot;: &quot;8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254&quot;
        ///          }
        ///        }        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pip_report_multi_pkg {
            get {
                return ResourceManager.GetString("pip_report_multi_pkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1&quot;,
        ///  &quot;pip_version&quot;: &quot;24.0&quot;,
        ///  &quot;install&quot;: [
        ///    {
        ///      &quot;download_info&quot;: {
        ///        &quot;url&quot;: &quot;https://files.pythonhosted.org/packages/f9/9b/335f9764261e915ed497fcdeb11df5dfd6f7bf257d4a6a2a686d80da4d54/requests-2.32.3-py3-none-any.whl&quot;,
        ///        &quot;archive_info&quot;: {
        ///          &quot;hash&quot;: &quot;sha256=70761cfe03c773ceb22aa2f671b4757976145175cdfca038c02654d061d6dcc6&quot;,
        ///          &quot;hashes&quot;: {
        ///            &quot;sha256&quot;: &quot;70761cfe03c773ceb22aa2f671b4757976145175cdfca038c02654d061d6dcc6&quot;
        ///          }
        ///        } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pip_report_simple_extras {
            get {
                return ResourceManager.GetString("pip_report_simple_extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1&quot;,
        ///  &quot;pip_version&quot;: &quot;24.0&quot;,
        ///  &quot;install&quot;: [
        ///    {
        ///      &quot;download_info&quot;: {
        ///        &quot;url&quot;: &quot;https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl&quot;,
        ///        &quot;archive_info&quot;: {
        ///          &quot;hash&quot;: &quot;sha256=8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254&quot;,
        ///          &quot;hashes&quot;: {
        ///            &quot;sha256&quot;: &quot;8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254&quot;
        ///          }
        ///        }        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pip_report_single_pkg {
            get {
                return ResourceManager.GetString("pip_report_single_pkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;2&quot;,
        ///  &quot;pip_version&quot;: &quot;24.0&quot;,
        ///  &quot;install&quot;: [
        ///    {
        ///      &quot;download_info&quot;: {
        ///        &quot;url&quot;: &quot;https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl&quot;,
        ///        &quot;archive_info&quot;: {
        ///          &quot;hash&quot;: &quot;sha256=8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254&quot;,
        ///          &quot;hashes&quot;: {
        ///            &quot;sha256&quot;: &quot;8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254&quot;
        ///          }
        ///        }        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pip_report_single_pkg_bad_version {
            get {
                return ResourceManager.GetString("pip_report_single_pkg_bad_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1&quot;,
        ///  &quot;pip_version&quot;: &quot;24.0&quot;,
        ///  &quot;install&quot;: [
        ///    {
        ///      &quot;download_info&quot;: {
        ///        &quot;url&quot;: &quot;https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl&quot;,
        ///        &quot;archive_info&quot;: {
        ///          &quot;hash&quot;: &quot;sha256=8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254&quot;,
        ///          &quot;hashes&quot;: {
        ///            &quot;sha256&quot;: &quot;8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254&quot;
        ///          }
        ///        }        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pip_report_single_pkg_invalid_pkg_version {
            get {
                return ResourceManager.GetString("pip_report_single_pkg_invalid_pkg_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: 3,
        ///  &quot;targets&quot;: {
        ///    &quot;.NETCoreApp,Version=v1.1&quot;: {
        ///      &quot;Libuv/1.9.1&quot;: {
        ///        &quot;type&quot;: &quot;package&quot;,
        ///        &quot;dependencies&quot;: {
        ///          &quot;Microsoft.NETCore.Platforms&quot;: &quot;1.0.1&quot;
        ///        },
        ///        &quot;runtimeTargets&quot;: {
        ///          &quot;runtimes/debian-x64/native/libuv.so&quot;: {
        ///            &quot;assetType&quot;: &quot;native&quot;,
        ///            &quot;rid&quot;: &quot;debian-x64&quot;
        ///          },
        ///          &quot;runtimes/fedora-x64/native/libuv.so&quot;: {
        ///            &quot;assetType&quot;: &quot;native&quot;,
        ///            &quot;rid&quot;: &quot;fedora-x64&quot;
        ///          },
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_1_1_console {
            get {
                return ResourceManager.GetString("project_assets_1_1_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: 3,
        ///  &quot;targets&quot;: {
        ///    &quot;.NETCoreApp,Version=v1.1&quot;: {
        ///      &quot;Libuv/1.9.2&quot;: {
        ///        &quot;type&quot;: &quot;package&quot;,
        ///        &quot;dependencies&quot;: {
        ///          &quot;Microsoft.NETCore.Platforms&quot;: &quot;1.0.1&quot;
        ///        },
        ///        &quot;runtimeTargets&quot;: {
        ///          &quot;runtimes/debian-x64/native/libuv.so&quot;: {
        ///            &quot;assetType&quot;: &quot;native&quot;,
        ///            &quot;rid&quot;: &quot;debian-x64&quot;
        ///          },
        ///          &quot;runtimes/osx/native/libuv.dylib&quot;: {
        ///            &quot;assetType&quot;: &quot;native&quot;,
        ///            &quot;rid&quot;: &quot;osx&quot;
        ///          },
        ///          &quot;r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_1_1_web {
            get {
                return ResourceManager.GetString("project_assets_1_1_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: 3,
        ///  &quot;targets&quot;: {
        ///    &quot;.NETCoreApp,Version=v2.1&quot;: {
        ///      &quot;Microsoft.AspNet.WebApi.Client/5.2.6&quot;: {
        ///        &quot;type&quot;: &quot;package&quot;,
        ///        &quot;dependencies&quot;: {
        ///          &quot;Newtonsoft.Json&quot;: &quot;10.0.1&quot;,
        ///          &quot;Newtonsoft.Json.Bson&quot;: &quot;1.0.1&quot;
        ///        },
        ///        &quot;compile&quot;: {
        ///          &quot;lib/netstandard2.0/System.Net.Http.Formatting.dll&quot;: {}
        ///        },
        ///        &quot;runtime&quot;: {
        ///          &quot;lib/netstandard2.0/System.Net.Http.Formatting.dll&quot;: {}
        ///        }
        ///      },
        ///      &quot;Microsoft.AspNetCore/2.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_2_1_web {
            get {
                return ResourceManager.GetString("project_assets_2_1_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;version&quot;: 3,
        ///	&quot;targets&quot;: {
        ///		&quot;.NETCoreApp,Version=v2.2&quot;: {
        ///			&quot;CommandLineParser/2.8.0&quot;: {
        ///				&quot;type&quot;: &quot;package&quot;,
        ///				&quot;compile&quot;: {
        ///					&quot;lib/netstandard2.0/_._&quot;: {}
        ///				},
        ///				&quot;runtime&quot;: {
        ///					&quot;lib/netstandard2.0/CommandLine.dll&quot;: {}
        ///				}
        ///			},
        ///			&quot;coverlet.msbuild/2.5.1&quot;: {
        ///				&quot;type&quot;: &quot;package&quot;,
        ///				&quot;build&quot;: {
        ///					&quot;build/netstandard2.0/coverlet.msbuild.props&quot;: {},
        ///					&quot;build/netstandard2.0/coverlet.msbuild.targets&quot;: {}
        ///				}
        ///			},
        ///			&quot;DotNet.Glob/2.1.1&quot;: {
        ///				&quot;type&quot;: &quot;package [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_2_2 {
            get {
                return ResourceManager.GetString("project_assets_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;version&quot;: 3,
        ///	&quot;targets&quot;: {
        ///	  &quot;.NETCoreApp,Version=v2.2&quot;: {
        ///		&quot;coverlet.msbuild/2.5.1&quot;: {
        ///		  &quot;type&quot;: &quot;package&quot;,
        ///		  &quot;build&quot;: {
        ///			&quot;build/netstandard2.0/coverlet.msbuild.props&quot;: {},
        ///			&quot;build/netstandard2.0/coverlet.msbuild.targets&quot;: {}
        ///		  }
        ///		},
        ///		&quot;DotNet.Glob/2.1.1&quot;: {
        ///		  &quot;type&quot;: &quot;package&quot;,
        ///		  &quot;dependencies&quot;: {
        ///			&quot;NETStandard.Library&quot;: &quot;1.6.1&quot;
        ///		  },
        ///		  &quot;compile&quot;: {
        ///			&quot;lib/netstandard1.1/DotNet.Glob.dll&quot;: {}
        ///		  },
        ///		  &quot;runtime&quot;: {
        ///			&quot;lib/netstandard1.1/DotNet.Glob.dll&quot;: {}        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_2_2_additional {
            get {
                return ResourceManager.GetString("project_assets_2_2_additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;version&quot;: 3,
        ///    &quot;targets&quot;: {
        ///      &quot;.NETCoreApp,Version=v3.1&quot;: {
        ///        &quot;Microsoft.Extensions.DependencyModel/3.0.0&quot;: {
        ///          &quot;type&quot;: &quot;package&quot;,
        ///          &quot;dependencies&quot;: {
        ///            &quot;System.Text.Json&quot;: &quot;4.6.0&quot;
        ///          },
        ///          &quot;compile&quot;: {
        ///            &quot;lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll&quot;: {}
        ///          },
        ///          &quot;runtime&quot;: {
        ///            &quot;lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll&quot;: {}
        ///          }
        ///        },
        ///        &quot;Microsoft. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_3_1 {
            get {
                return ResourceManager.GetString("project_assets_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: 3,
        ///  &quot;targets&quot;: {
        ///    &quot;net42.15&quot;: {
        ///      &quot;Microsoft.Extensions.Caching.Abstractions/9.0.0&quot;: {
        ///        &quot;type&quot;: &quot;package&quot;,
        ///        &quot;dependencies&quot;: {
        ///          &quot;Microsoft.Extensions.Primitives&quot;: &quot;9.0.0&quot;
        ///        },
        ///        &quot;compile&quot;: {
        ///          &quot;lib/net9.0/Microsoft.Extensions.Caching.Abstractions.dll&quot;: {
        ///            &quot;related&quot;: &quot;.xml&quot;
        ///          }
        ///        },
        ///        &quot;runtime&quot;: {
        ///          &quot;lib/net9.0/Microsoft.Extensions.Caching.Abstractions.dll&quot;: {
        ///            &quot;related&quot;: &quot;.xml&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_42_15_web {
            get {
                return ResourceManager.GetString("project_assets_42_15_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: 3,
        ///  &quot;targets&quot;: {
        ///    &quot;net6.0&quot;: {
        ///      &quot;Microsoft.Extensions.Primitives/6.0.0&quot;: {
        ///        &quot;type&quot;: &quot;package&quot;,
        ///        &quot;dependencies&quot;: {
        ///          &quot;System.Runtime.CompilerServices.Unsafe&quot;: &quot;6.0.0&quot;
        ///        },
        ///        &quot;compile&quot;: {
        ///          &quot;lib/net6.0/Microsoft.Extensions.Primitives.dll&quot;: {
        ///            &quot;related&quot;: &quot;.xml&quot;
        ///          }
        ///        },
        ///        &quot;runtime&quot;: {
        ///          &quot;lib/net6.0/Microsoft.Extensions.Primitives.dll&quot;: {
        ///            &quot;related&quot;: &quot;.xml&quot;
        ///          }
        ///        },        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_6_0_8_0_multi_framework {
            get {
                return ResourceManager.GetString("project_assets_6_0_8_0_multi_framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: 3,
        ///  &quot;targets&quot;: {
        ///    &quot;net8.0&quot;: {
        ///      &quot;Microsoft.Extensions.Primitives/6.0.0&quot;: {
        ///        &quot;type&quot;: &quot;package&quot;,
        ///        &quot;dependencies&quot;: {
        ///          &quot;System.Runtime.CompilerServices.Unsafe&quot;: &quot;6.0.0&quot;
        ///        },
        ///        &quot;compile&quot;: {
        ///          &quot;lib/net6.0/Microsoft.Extensions.Primitives.dll&quot;: {
        ///            &quot;related&quot;: &quot;.xml&quot;
        ///          }
        ///        },
        ///        &quot;runtime&quot;: {
        ///          &quot;lib/net6.0/Microsoft.Extensions.Primitives.dll&quot;: {
        ///            &quot;related&quot;: &quot;.xml&quot;
        ///          }
        ///        },        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_8_0_multi_framework {
            get {
                return ResourceManager.GetString("project_assets_8_0_multi_framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: 3,
        ///  &quot;targets&quot;: {
        ///    &quot;net8.0&quot;: {
        ///      &quot;Microsoft.Extensions.Caching.Abstractions/8.0.0&quot;: {
        ///        &quot;type&quot;: &quot;package&quot;,
        ///        &quot;dependencies&quot;: {
        ///          &quot;Microsoft.Extensions.Primitives&quot;: &quot;8.0.0&quot;
        ///        },
        ///        &quot;compile&quot;: {
        ///          &quot;lib/net8.0/Microsoft.Extensions.Caching.Abstractions.dll&quot;: {
        ///            &quot;related&quot;: &quot;.xml&quot;
        ///          }
        ///        },
        ///        &quot;runtime&quot;: {
        ///          &quot;lib/net8.0/Microsoft.Extensions.Caching.Abstractions.dll&quot;: {
        ///            &quot;related&quot;: &quot;.xml&quot;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_8_0_web {
            get {
                return ResourceManager.GetString("project_assets_8_0_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: 3,
        ///  &quot;targets&quot;: {
        ///    &quot;.NETFramework,Version=v4.7.2&quot;: {},
        ///    &quot;net8.0&quot;: {}
        ///  },
        ///  &quot;libraries&quot;: {},
        ///  &quot;projectFileDependencyGroups&quot;: {
        ///    &quot;.NETFramework,Version=v4.7.2&quot;: [],
        ///    &quot;net8.0&quot;: []
        ///  },
        ///  &quot;packageFolders&quot;: {
        ///    &quot;C:\\Users\\username\\.nuget\\packages\\&quot;: {},
        ///    &quot;C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\NuGetPackages&quot;: {}
        ///  },
        ///  &quot;project&quot;: {
        ///    &quot;version&quot;: &quot;1.0.0&quot;,
        ///    &quot;restore&quot;: {
        ///      &quot;projectUniqueName&quot;: &quot;C:\\src\\packageDownloadSample\\package [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_packageDownload {
            get {
                return ResourceManager.GetString("project_assets_packageDownload", resourceCulture);
            }
        }
    }
}
