//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ComponentDetection.Detectors.Tests.Mocks {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.ComponentDetection.Detectors.Tests.Mocks.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to integrationTestCompileClasspath - Compile classpath for source set &apos;integration test&apos;.
        ///+--- commons-io:commons-io:2.5
        ///+--- org.kohsuke:github-api:1.94
        ///|    +--- org.apache.commons:commons-lang3:3.7
        ///|    +--- commons-codec:commons-codec:1.7
        ///|    +--- com.fasterxml.jackson.core:jackson-databind:2.9.2
        ///|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0
        ///|    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.2
        ///|    \--- commons-io:commons-io:1.4 -&gt; 2.5
        ///+--- org.zeroturnaround:zt-zip: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GradlewDependencyOutput {
            get {
                return ResourceManager.GetString("GradlewDependencyOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to org.apache.maven:maven-compat:jar:3.6.1-SNAPSHOT
        ///+- org.apache.maven:maven-model:jar:3.6.1-SNAPSHOT:compile
        ///+- org.apache.maven:maven-model-builder:jar:3.6.1-SNAPSHOT:compile
        ///|  \- org.apache.maven:maven-builder-support:jar:3.6.1-SNAPSHOT:compile
        ///+- org.apache.maven:maven-settings:jar:3.6.1-SNAPSHOT:compile
        ///+- org.apache.maven:maven-settings-builder:jar:3.6.1-SNAPSHOT:compile
        ///|  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4:compile
        ///|     \- org.sonatype.plexus:plexus-cipher:jar:1.7:compile
        ///+- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MvnCliDependencyOutput {
            get {
                return ResourceManager.GetString("MvnCliDependencyOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;version&quot;: 3,
        ///	&quot;targets&quot;: {
        ///		&quot;.NETCoreApp,Version=v2.2&quot;: {
        ///			&quot;CommandLineParser/2.8.0&quot;: {
        ///				&quot;type&quot;: &quot;package&quot;,
        ///				&quot;compile&quot;: {
        ///					&quot;lib/netstandard2.0/_._&quot;: {}
        ///				},
        ///				&quot;runtime&quot;: {
        ///					&quot;lib/netstandard2.0/CommandLine.dll&quot;: {}
        ///				}
        ///			},
        ///			&quot;coverlet.msbuild/2.5.1&quot;: {
        ///				&quot;type&quot;: &quot;package&quot;,
        ///				&quot;build&quot;: {
        ///					&quot;build/netstandard2.0/coverlet.msbuild.props&quot;: {},
        ///					&quot;build/netstandard2.0/coverlet.msbuild.targets&quot;: {}
        ///				}
        ///			},
        ///			&quot;DotNet.Glob/2.1.1&quot;: {
        ///				&quot;type&quot;: &quot;package [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_2_2 {
            get {
                return ResourceManager.GetString("project_assets_2_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;version&quot;: 3,
        ///	&quot;targets&quot;: {
        ///	  &quot;.NETCoreApp,Version=v2.2&quot;: {
        ///		&quot;coverlet.msbuild/2.5.1&quot;: {
        ///		  &quot;type&quot;: &quot;package&quot;,
        ///		  &quot;build&quot;: {
        ///			&quot;build/netstandard2.0/coverlet.msbuild.props&quot;: {},
        ///			&quot;build/netstandard2.0/coverlet.msbuild.targets&quot;: {}
        ///		  }
        ///		},
        ///		&quot;DotNet.Glob/2.1.1&quot;: {
        ///		  &quot;type&quot;: &quot;package&quot;,
        ///		  &quot;dependencies&quot;: {
        ///			&quot;NETStandard.Library&quot;: &quot;1.6.1&quot;
        ///		  },
        ///		  &quot;compile&quot;: {
        ///			&quot;lib/netstandard1.1/DotNet.Glob.dll&quot;: {}
        ///		  },
        ///		  &quot;runtime&quot;: {
        ///			&quot;lib/netstandard1.1/DotNet.Glob.dll&quot;: {}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_2_2_additional {
            get {
                return ResourceManager.GetString("project_assets_2_2_additional", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;version&quot;: 3,
        ///    &quot;targets&quot;: {
        ///      &quot;.NETCoreApp,Version=v3.1&quot;: {
        ///        &quot;Microsoft.Extensions.DependencyModel/3.0.0&quot;: {
        ///          &quot;type&quot;: &quot;package&quot;,
        ///          &quot;dependencies&quot;: {
        ///            &quot;System.Text.Json&quot;: &quot;4.6.0&quot;
        ///          },
        ///          &quot;compile&quot;: {
        ///            &quot;lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll&quot;: {}
        ///          },
        ///          &quot;runtime&quot;: {
        ///            &quot;lib/netstandard2.0/Microsoft.Extensions.DependencyModel.dll&quot;: {}
        ///          }
        ///        },
        ///        &quot;Microsoft. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_assets_3_1 {
            get {
                return ResourceManager.GetString("project_assets_3_1", resourceCulture);
            }
        }
    }
}
