namespace Microsoft.ComponentDetection.Detectors.NuGet;

using global::NuGet.Frameworks;

/// <summary>
/// Framework packages for net9.0.
/// </summary>
internal partial class FrameworkPackages
{
    internal static class NETCoreApp90
    {
        internal static FrameworkPackages Instance { get; } = new(NuGetFramework.Parse("net9.0"), NETCoreApp80.Instance)
        {
            { "Microsoft.VisualBasic", "10.4.0" },
            { "runtime.debian.8-x64.runtime.native.System", "4.3.1" },
            { "runtime.debian.8-x64.runtime.native.System.IO.Compression", "4.3.2" },
            { "runtime.debian.8-x64.runtime.native.System.Net.Http", "4.3.1" },
            { "runtime.debian.8-x64.runtime.native.System.Net.Security", "4.3.1" },
            { "runtime.debian.8-x64.runtime.native.System.Security.Cryptography", "4.3.4" },
            { "runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl", "4.3.3" },
            { "runtime.fedora.23-x64.runtime.native.System", "4.3.1" },
            { "runtime.fedora.23-x64.runtime.native.System.IO.Compression", "4.3.2" },
            { "runtime.fedora.23-x64.runtime.native.System.Net.Http", "4.3.1" },
            { "runtime.fedora.23-x64.runtime.native.System.Net.Security", "4.3.1" },
            { "runtime.fedora.23-x64.runtime.native.System.Security.Cryptography", "4.3.4" },
            { "runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl", "4.3.3" },
            { "runtime.fedora.24-x64.runtime.native.System", "4.3.1" },
            { "runtime.fedora.24-x64.runtime.native.System.IO.Compression", "4.3.2" },
            { "runtime.fedora.24-x64.runtime.native.System.Net.Http", "4.3.1" },
            { "runtime.fedora.24-x64.runtime.native.System.Net.Security", "4.3.1" },
            { "runtime.fedora.24-x64.runtime.native.System.Security.Cryptography", "4.3.4" },
            { "runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl", "4.3.3" },
            { "runtime.opensuse.13.2-x64.runtime.native.System", "4.3.1" },
            { "runtime.opensuse.13.2-x64.runtime.native.System.IO.Compression", "4.3.2" },
            { "runtime.opensuse.13.2-x64.runtime.native.System.Net.Http", "4.3.1" },
            { "runtime.opensuse.13.2-x64.runtime.native.System.Net.Security", "4.3.1" },
            { "runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography", "4.3.4" },
            { "runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl", "4.3.3" },
            { "runtime.opensuse.42.1-x64.runtime.native.System", "4.3.1" },
            { "runtime.opensuse.42.1-x64.runtime.native.System.IO.Compression", "4.3.2" },
            { "runtime.opensuse.42.1-x64.runtime.native.System.Net.Http", "4.3.1" },
            { "runtime.opensuse.42.1-x64.runtime.native.System.Net.Security", "4.3.1" },
            { "runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography", "4.3.4" },
            { "runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl", "4.3.3" },
            { "runtime.osx.10.10-x64.runtime.native.System", "4.3.1" },
            { "runtime.osx.10.10-x64.runtime.native.System.IO.Compression", "4.3.2" },
            { "runtime.osx.10.10-x64.runtime.native.System.Net.Http", "4.3.1" },
            { "runtime.osx.10.10-x64.runtime.native.System.Net.Security", "4.3.1" },
            { "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography", "4.3.4" },
            { "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple", "4.3.1" },
            { "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl", "4.3.3" },
            { "runtime.rhel.7-x64.runtime.native.System", "4.3.1" },
            { "runtime.rhel.7-x64.runtime.native.System.IO.Compression", "4.3.2" },
            { "runtime.rhel.7-x64.runtime.native.System.Net.Http", "4.3.1" },
            { "runtime.rhel.7-x64.runtime.native.System.Net.Security", "4.3.1" },
            { "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography", "4.3.4" },
            { "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl", "4.3.3" },
            { "runtime.ubuntu.14.04-x64.runtime.native.System", "4.3.1" },
            { "runtime.ubuntu.14.04-x64.runtime.native.System.IO.Compression", "4.3.2" },
            { "runtime.ubuntu.14.04-x64.runtime.native.System.Net.Http", "4.3.1" },
            { "runtime.ubuntu.14.04-x64.runtime.native.System.Net.Security", "4.3.1" },
            { "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography", "4.3.4" },
            { "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl", "4.3.3" },
            { "runtime.ubuntu.16.04-x64.runtime.native.System", "4.3.1" },
            { "runtime.ubuntu.16.04-x64.runtime.native.System.IO.Compression", "4.3.2" },
            { "runtime.ubuntu.16.04-x64.runtime.native.System.Net.Http", "4.3.1" },
            { "runtime.ubuntu.16.04-x64.runtime.native.System.Net.Security", "4.3.1" },
            { "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography", "4.3.4" },
            { "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl", "4.3.3" },
            { "runtime.ubuntu.16.10-x64.runtime.native.System", "4.3.1" },
            { "runtime.ubuntu.16.10-x64.runtime.native.System.IO.Compression", "4.3.2" },
            { "runtime.ubuntu.16.10-x64.runtime.native.System.Net.Http", "4.3.1" },
            { "runtime.ubuntu.16.10-x64.runtime.native.System.Net.Security", "4.3.1" },
            { "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography", "4.3.4" },
            { "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl", "4.3.3" },
            { "System.Buffers", "5.0.0" },
            { "System.Collections.Immutable", "9.0.0" },
            { "System.Diagnostics.DiagnosticSource", "9.0.0" },
            { "System.Formats.Asn1", "9.0.0" },
            { "System.Formats.Tar", "9.0.0" },
            { "System.IO.Pipelines", "9.0.0" },
            { "System.Memory", "5.0.0" },
            { "System.Net.Http.Json", "9.0.0" },
            { "System.Numerics.Vectors", "5.0.0" },
            { "System.Private.Uri", "4.3.2" },
            { "System.Reflection.DispatchProxy", "6.0.0" },
            { "System.Reflection.Metadata", "9.0.0" },
            { "System.Runtime.CompilerServices.Unsafe", "7.0.0" },
            { "System.Text.Encoding.CodePages", "9.0.0" },
            { "System.Text.Encodings.Web", "9.0.0" },
            { "System.Text.Json", "9.0.0" },
            { "System.Threading.Channels", "9.0.0" },
            { "System.Threading.Tasks.Dataflow", "9.0.0" },
            { "System.Threading.Tasks.Extensions", "5.0.0" },
            { "System.Xml.XPath.XDocument", "5.0.0" },
        };
    }
}
