name: Feature request
about: Suggest an idea for this project
title: '[Feature]: '
labels: ['triage', 'enhancement']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: input
    id: summary
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context, alternatives considered, etc.
      description: Add any other context or screenshots about the feature request here.
