namespace Microsoft.ComponentDetection.Detectors.Maven;

/// <summary>
/// Shared constants for Maven detectors.
/// </summary>
public static class MavenConstants
{
    /// <summary>
    /// The filename for Maven CLI dependency output files.
    /// This file is generated by MavenCommandService and consumed by Maven detectors.
    /// </summary>
    public const string BcdeMvnDependencyFileName = "bcde.mvndeps";

    /// <summary>
    /// Detector ID for MvnCliComponentDetector.
    /// </summary>
    public const string MvnCliDetectorId = "MvnCli";
}
