namespace Microsoft.ComponentDetection.Detectors.DotNet;

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using global::NuGet.ProjectModel;
using Microsoft.ComponentDetection.Contracts;
using Microsoft.ComponentDetection.Contracts.Internal;
using Microsoft.ComponentDetection.Contracts.TypedComponent;
using Microsoft.Extensions.Logging;

public class DotNetComponentDetector : FileComponentDetector
{
    private readonly DotNetProjectInfoProvider projectInfoProvider;
    private readonly LockFileFormat lockFileFormat = new();

    public DotNetComponentDetector(
        IComponentStreamEnumerableFactory componentStreamEnumerableFactory,
        ICommandLineInvocationService commandLineInvocationService,
        IDirectoryUtilityService directoryUtilityService,
        IFileUtilityService fileUtilityService,
        IPathUtilityService pathUtilityService,
        IObservableDirectoryWalkerFactory walkerFactory,
        ILogger<DotNetComponentDetector> logger)
    {
        this.ComponentStreamEnumerableFactory = componentStreamEnumerableFactory;
        this.Scanner = walkerFactory;
        this.Logger = logger;
        this.projectInfoProvider = new DotNetProjectInfoProvider(
            commandLineInvocationService,
            directoryUtilityService,
            fileUtilityService,
            pathUtilityService,
            logger);
    }

    public override string Id => "DotNet";

    public override IList<string> SearchPatterns { get; } = [LockFileFormat.AssetsFileName];

    public override IEnumerable<ComponentType> SupportedComponentTypes => [ComponentType.DotNet];

    public override int Version { get; } = 1;

    public override IEnumerable<string> Categories => ["DotNet"];

    public override Task<IndividualDetectorScanResult> ExecuteDetectorAsync(ScanRequest request, CancellationToken cancellationToken = default)
    {
        this.projectInfoProvider.Initialize(request.SourceDirectory.FullName, request.SourceFileRoot?.FullName);
        return base.ExecuteDetectorAsync(request, cancellationToken);
    }

    protected override async Task OnFileFoundAsync(ProcessRequest processRequest, IDictionary<string, string> detectorArgs, CancellationToken cancellationToken = default)
    {
        var lockFile = this.lockFileFormat.Read(processRequest.ComponentStream.Stream, processRequest.ComponentStream.Location);

        if (lockFile.PackageSpec is null || lockFile.PackageSpec.RestoreMetadata is null)
        {
            // The lock file is not valid, or does not contain a PackageSpec.
            // This could be due to the lock file being generated by a different version of the SDK.
            // We should not fail the detector, but we should log a warning.
            this.Logger.LogWarning("Lock file {LockFilePath} does not contain project information.", processRequest.ComponentStream.Location);
            return;
        }

        await this.projectInfoProvider.RegisterDotNetComponentsAsync(
            lockFile,
            processRequest.ComponentStream.Location,
            this.ComponentRecorder,
            cancellationToken);
    }
}
