name: "Detector version bump reminder"
on:
  push:
    paths:
      - "src/Microsoft.ComponentDetection.Detectors/**"

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - uses: mshick/add-pr-comment@011b026a3c7232d6216bd04f2300f821dab95f3a # v3.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            👋 Hi! It looks like you modified some files in the `Detectors` folder.
            You may need to bump the detector versions if any of the following scenarios apply:
            * The detector detects more or fewer components than before
            * The detector generates different parent/child graph relationships than before
            * The detector generates different `devDependencies` values than before

            If none of the above scenarios apply, feel free to ignore this comment 🙂
