name: "Detector version bump reminder"
on:
  push:
    paths:
      - "src/Microsoft.ComponentDetection.Detectors/**"

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: mshick/add-pr-comment@ffd016c7e151d97d69d21a843022fd4cd5b96fe5 # v3.9.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            👋 Hi! It looks like you modified some files in the `Detectors` folder.
            You may need to bump the detector versions if any of the following scenarios apply:
            * The detector detects more or fewer components than before
            * The detector generates different parent/child graph relationships than before
            * The detector generates different `devDependencies` values than before

            If none of the above scenarios apply, feel free to ignore this comment 🙂
