name: Sync issue to Azure DevOps work item

on:
  workflow_dispatch:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]

permissions: {}

jobs:
  alert:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@3072da42abf94ebe4c7778c57fb4af06db341c72 # v2.2
        env:
          ado_token: "${{ secrets.ADO_ISSUE_SYNC_TOKEN }}" # Work items write permissions
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          ado_organization: "mseng"
          ado_project: "AzureDevOps"
          ado_area_path: "AzureDevOps\\Artifacts\\Component Governance"
          ado_wit: "Task"
          ado_new_state: "Proposed"
          ado_active_state: "In Progress"
          ado_close_state: "Completed"
